spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/abobrov
    username: abobrov
    password:
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      schema-locations: /scripts/data.sql
